### ISSUE TITLE
VV - Place the "Think this issue needs more voices" such that it does not hamper the Page content formatting

### ISSUE THREAD

**Issue by pratsajency** [ajency/Thisandthat#26]
Currently the contents are misaligned because of the way the "Think this issue needs more voices" is placed on the page.

Ex: Refer this page - http://www.videovolunteers.org/?p=11598&preview=true

Check what's the best way to handle this issue,
We can opt to reformat this and display the section at the end of the page contents.

![22](https://cloud.githubusercontent.com/assets/3326712/5857661/7c771bf4-a273-11e4-941f-fea18bd2833c.png)

**Comment by jeromie** [comment]
Link provided above returns 404 error. Not clear on what the issue is here. Is the layout broken on desktop or is this a mobile issue? On the below link, the layout seems ok to me. http://www.videovolunteers.org/women-of-chattisgarh-fight-for-equal-pay-after-eviction/

![women of chattisgarh fight for equal pay after eviction](https://cloud.githubusercontent.com/assets/5372828/6145920/f4e9889e-b20c-11e4-87ab-f49fe27f8ae0.png)

**Comment by pratsajency** [comment]
@jeromie 
Kindly login to the site and view the preview page.
Where i have provided an example, how the page contents get distorted due to "Think this issue needs more voices"

**Comment by jeromie** [comment]
@pratsajency issue resolved. Was a php task so used supresh's help.
